apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: xnemect-surgeon-ufe
spec:
  module-uri:
    http://xnemect-surgeon-ufe.wac-hospital/build/surgeon-ufe.esm.js
    # module web komponentu pre tento mikroFE
    # - umiestnený v namespace wac-hospital
  navigation:
    - element:
        xnemect-surgeon-app # element, ktorý bude vložený na stránku
        # pri navigácii na zoznam čakajúcich
      attributes:
        - name: api-base
          value: /xnemect-api
        - name: surgeon-id
          value: bobulova
      path: xnemect-surgeon # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny
      title: Zoznam chirurgov xnemect # názov mikro aplikácie
      details: Spravuje zoznam chuirurgov a ich zakrokov
  preload: false # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy:
    true # pre komponenty v rámci klastra, neprístupné na verejnej sieti
    # musí byť táto hodnota nastavená na true
  hash-suffix:
    v1alpha2 # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou
    # sa mení názov URL pre modul a tým je možné predísť problémom
    # s verziami vo vyrovnávacích pamätiach
