apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
  - name: xnemect/surgeon-ufe
    newName: xnemect/surgeon-ufe
    newTag: 1.1.9 #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
  - name: xnemect/surgeon-wl-webapi
    newName: xnemect/surgeon-wl-webapi
    newTag: 1.1.7
replacements:
  - targets:
      - select:
          group: fe.milung.eu
          version: v1
          kind: WebComponent
          name: xnemect-surgeon-ufe
        fieldPaths:
          - spec.hash-suffix
    source:
      version: v1
      kind: Deployment
      name: xnemect-surgeon-ufe-deployment
      fieldPath: spec.template.spec.containers.0.image
      options:
        delimiter: ":"
        index: 1
