apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: wac-hospital

namespace: wac-hospital

resources:
  - prepare.kustomization.yaml
  - cd.kustomization.yaml
  - install.kustomization.yaml
  - git-repository.yaml
