apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: wac-hospital

namespace: wac-hospital

resources:
  - prepare.kustomization.yaml
  - cd.kustomization.yaml
  - install.kustomization.yaml
  - git-repository.yaml
  - surgeon-ufe.image-repository.yaml
  - surgeon-ufe.image-policy.yaml
  - ufe-controller.image-repository.yaml
  - ufe-controller.image-policy.yaml
  - image-update-automation.yaml
  - surgeon-webapi.image-repository.yaml
  - surgeon-webapi.image-policy.yaml
