apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

commonLabels:
  app.kubernetes.io/part-of: wac-hospital
  app.kubernetes.io/name: xnemect-surgeon-wl

resources:
  - ../../../apps/xnemect-surgeon-ufe
  - ../../../apps/xnemect-surgeon-webapi

components:
  - ../../../components/version-release
