apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace:
  wac-hospital # chceme tieto objekty umiestniť do `wac-hospital` namespace
  # tento zapis preťaží hodnoty "namespace" vo všetkých objektoch

commonLabels:
  app.kubernetes.io/part-of: wac-hospital

resources:
  - ../../../apps/xnemect-surgeon-ufe

components:
  - ../../../components/version-developers
