apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml # namespace je tiež objektom pre tento klaster
  - ../../../infrastructure/ufe-controller # kustomization pre ufe-controller
  - ../../../infrastructure/fluxcd

patches:
  - path: patches/ufe-controller.service.yaml # úprava služby ufe-controller

components:
  - ../../../components/version-developers
