apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "https://github.com/xnemect1/surgeon-webapi//deployments/kustomize/install" # ?ref=v1.0.1
  - openapi-ui.service.yaml
  - http-route.yaml

patches:
  - path: patches/surgeon-webapi.deployment.yaml
