kind: Service
apiVersion: v1
metadata:
  name: xnemect-openapi-ui
spec:
  selector:
    pod: xnemect-surgeon-webapi-label
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
